INSERT INTO `#__jacomment_configs` VALUES (22, 'general', 'display_message=\nis_notify_admin=1\nis_notify_author=1\nis_enabled_email=1\nccemail=\naccess=0\nis_comment_offline=0\nmail_view_only=0\nis_use_ja_login_form=0\n\n');
INSERT INTO `#__jacomment_configs` VALUES (23, 'comments', 'is_enable_threads=1\nis_allow_voting=1\ntotal_attach_file=5\nmax_size_attach_file=2\nattach_file_type=doc,docx,pdf,txt,zip,rar,jpg,bmp,gif,png\nis_enable_website_field=1\nis_enable_autoexpanding=1\nis_extra_fields_expand=1\nis_enable_email_subscription=1\nis_allow_report=1\nis_allow_approve_new_comment=1\nmaximum_comment_in_item=100\nis_enable_rss=1\n\n');
INSERT INTO `#__jacomment_configs` VALUES (24, 'spamfilters', 'terms_of_usage=Registration to this forum is free! We do insist that you abide by the rules and policies detailed below. If you agree to the terms, please check the ''I agree'' checkbox and press the ''Register'' button below. If you would like to cancel the registration, click here to return to the forums index.\\n\\nForum Rules\\n\\nRegistration to this forum is free! We do insist that you abide by the rules and policies detailed below. If you agree to the terms, please check the ''I agree'' checkbox and press the ''Register'' button below. If you would like to cancel the registration, click here to return to the forums index.\nmin_length=10\nmax_length=1000\ncensored_words=\ncensored_words_replace=\nis_nofollow=1\nnumber_of_links=5\nis_enable_captcha_user=0\nis_use_akismet=0\n\n');
INSERT INTO `#__jacomment_configs` VALUES (25, 'blocked_word_list', '\ndamn');
INSERT INTO `#__jacomment_configs` VALUES (26, 'blacklist_word_list', '\nfuck');
INSERT INTO `#__jacomment_configs` VALUES (27, 'permissions', 'view=all\npost=all\nvote=all\ntype_voting=1\nreport=all\ntotal_to_report_spam=10\ntype_editing=1\n\n');
INSERT INTO `#__jacomment_configs` VALUES (28, 'layout', 'theme=default\nenable_avatar=1\ntype_avatar=0\navatar_size=3\nenable_youtube=1\nis_enable_website_field=0\nform_position=1\nenable_sorting_options=1\ndefault_sort=date\ndefault_sort_type=ASC\nenable_timestamp=1\nfooter_text=Copyright JAComment\ncustom_css=\nenable_login_rpx=1\nenable_addthis=1\ncustom_addthis=<!-- AddThis Button BEGIN --><a class="addthis_button" href="http://addthis.com/bookmark.php?v=250&pub=xa-4af3e1272f178ef0"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4af3e1272f178ef0"></script><!-- AddThis Button END -->\ncustom_addtoany=<a class="a2a_dd" href="http://www.addtoany.com/share_save"><img src="http://static.addtoany.com/buttons/share_save_171_16.png" width="171" height="16" border="0" alt="Share/Bookmark"/></a><script type="text/javascript">a2a_linkname=document.title;a2a_linkurl=location.href;</script><script type="text/javascript" src="http://static.addtoany.com/menu/page.js"></script>\ncustom_tweetmeme=<script type="text/javascript" src="http://tweetmeme.com/i/scripts/button.js"></script>\nenable_bbcode=1\nenable_smileys=1\nuse_default_avatar=0\nenable_login_button=0\nenable_subscribe_menu=0\nenable_user_rep_indicator=0\nenable_comment_form=0\nenable_addtoany=1\nenable_polldaddy=0\nenable_seesmic=0\nenable_tweetmeme=1\nenable_activity_stream=1\n\n');




INSERT INTO `#__jacomment_email_templates` (`id`, `name`, `title`, `subject`, `content`, `email_from_address`, `email_from_name`, `published`, `group`, `language`, `system`) VALUES
(10, 'mailheader', 'Header', 'Header', '', '', '', 1, 1, 'en-GB', 1),
(11, 'mailfooter', 'Footer', 'Footer', '<p style="margin: 15px 5px 2px 0pt; text-align: right; color: #aaaaaa"> powered by <span style="font-family: arial; font-style: normal; font-variant: normal; font-weight: normal; font-size: 16px; line-height: normal; font-size-adjust: none; font-stretch: normal; letter-spacing: -1px"><strong>JA<font color="#f47414">Comment</font></strong></span> </p>', '', '', 1, 1, 'en-GB', 1),
(35, 'Jacommentconfirmation_sent_to_new_comment_creator_need_admin_approved', 'Confirmation sent to new comment creator - In cases where admin approval is Required', 'Your comment is pending approval...', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that you have just created a new comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} with the following details: </p><p><strong>Comment URL</strong>: {ITEM_LINK} </p><p><strong>Comment details</strong>: {ITEM_DETAILS}.</p><p> Your comment shall be posted after being approved by administrator. Please check your mailbox periodically for updated information. </p><p>Sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(12, 'Jacommentnotify_to_user_new_voice_daily', 'Dailly NEW Comment statistics (to those who subscribe)', '[JA Comment] Daily statistics', '<p>Hi {USERS_USERNAME},</p><p>Here are a quick overview of what has been going on at JA Comment during the last 24 hours: </p>{ITEM_DETAILS}', '', '', 1, 0, 'en-GB', 1),
(19, 'Jacommentnotify_when_new_item_was_post', 'Notify when new item was post', 'Have a new comment!', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that a comment has been newly added into the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} with the following details: </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p>Please click on the link above to view the full details. </p><p>Sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(22, 'Jacommentnotifying_admin_on_a_new_comment_posted', 'Notifying admin on a new comment posted', 'A new comment has been newly added', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform you that a new comment on {ITEM_TITLE_WITH_LINK} has newly been added at {CONFIG.SITE_TITLE} with the following details: </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p><strong>Comment creator:</strong> {ITEM_CREATE_BY} </p><p>Please review the above comments and take appropriate actions as soon as possible. </p><p>Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(34, 'Jacommentconfirmation_sent_to_new_comment_creator_dont_need_admin_approved', 'Confirmation sent to new comment creator - In cases where admin approval is NOT required', 'We confirm your comment', '<p>Dear {USERS_USERNAME}, </p><p>This email is to confirm that you have successfully created a new comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} with the following details: </p><p> <strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS}.</p><p>Please check your mailbox periodically as we shall notify you if there is any new reply on this issue.</p><p> Sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(24, 'Jacommentnotifying_comment_creator_if_there_is_a_new_reply_to_his_comment', 'Notifying comment creator if there is a new reply to his comment', 'A new reply has just been posted on your comment', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that a new reply has just been posted on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} with the following details: </p><p><strong>Reply URL</strong>: {ITEM_LINK} </p><p><strong>Reply details</strong>: {ITEM_DETAILS} </p><p><strong>Reply creator:</strong> {REPLY_OWNER} . </p><p>Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(25, 'Jacommentnotifying_those_whose_comment_has_been_deleted', 'Notifying those whose comment has been deleted', 'Your comment has been deleted', '<p>Dear {USERS_USERNAME}, </p><p>We are sorry to inform that your comment on the issue "{ITEM_TITLE_WITH_LINK}” at {CONFIG.SITE_TITLE} has been deleted by {SITE_ADMIN} with the following reasons: </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p><strong>Moderate reasons:</strong> {MOD_REASONS} </p><p>Thank you for your understanding and do hope you carefully read the instructions and strictly follow the Terms of Use before posting any comments at {CONFIG.SITE_TITLE} in the time to come. </p><p>Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(26, 'Jacommentnotifying_those_whose_comment_has_been_approved', 'Notifying those whose comment has been approved', 'Your Comment has been approved', '<p>Dear {USERS_USERNAME}, </p><p> This email is to inform that your comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} has been approved and published by {SITE_ADMIN} with the following details: </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p>Please check your mailbox periodically as we shall notify you if there is any reply on this issue Yours. sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(27, 'Jacommentnotifying_admin_of_a_spam_report_on_a_comment', 'Notifying admin of a spam report on a comment', 'A comment has been reported as spam', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that the comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} has been reported as spam recently. </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p><strong>Spam reporter:</strong> {SPAM_REPORTER} </p><p>Kindly review the above comment to see if it is a spam as report or not for further action at your soonest time. </p><p>Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(28, 'Jacommentnotifying_those_whose_comment_is_reported_as_spam', 'Notifying those whose comment is reported as spam', 'You have comment reported as spam', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that your comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} has been reported as spam by other user recently. </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p><strong>Spam reporter:</strong> {SPAM_REPORTER} </p><p>The spam report shall be thoroughly and fairly reviewed by {SITE_ADMIN} before any further action. Kindly continue using our site normally and sorry for any inconveniences that may have caused. </p><p>Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(29, 'Jacommentnotifying_those_whose_comment_is_removed_as_spam_by_admin', 'Notifying those whose comment is removed as spam by admin', 'Your comment has been removed as spam by administrator', '<p>Dear {USERS_USERNAME},</p><p>This email is to inform that your comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} has been removed as spam by {SITE_ADMIN}. </p><p><strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p><strong>Moderate Reasons:</strong> {MOD_REASONS} </p><p> Thank you for your understanding and do hope you carefully read the instructions and strictly follow the Terms of Use before posting any comments at {CONFIG.SITE_TITLE} in the time to come.</p><p> Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(30, 'Jacommentnotifying_those_whose_comment_has_been_unapproved', 'Notifying those whose comment has been unapproved', 'You have a comment unapproved', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that your comment on the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} has been unapproved by {SITE_ADMIN} due to the following reasons:</p><p> <strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p><strong>Unapproved reasons:</strong> {UNAPPROVE_REASONS} </p><p>Thank you for your understanding and do hope you carefully read the instructions and strictly follow the Terms of Use before posting any comments at {CONFIG.SITE_TITLE} in the time to come. </p><p>Yours sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0),
(32, 'Jacommentnotifying_comment_creator_if_there_is_a_new_comment_on_the_issue', 'Notifying comment creator if there is a new comment on the issue', 'A new comment has been added', '<p>Dear {USERS_USERNAME}, </p><p>This email is to inform that a comment has been newly added into the issue {ITEM_TITLE_WITH_LINK} at {CONFIG.SITE_TITLE} with the following details:</p><p> <strong>Comment URL:</strong> {ITEM_LINK} </p><p><strong>Comment details:</strong> {ITEM_DETAILS} </p><p>Please click on the link above to view the full details. </p><p>Sincerely, {CONFIG.SITE_TITLE}</p>', '', '', 1, 0, 'en-GB', 0);

